### ISSUE TITLE
How to control the drone from an computer ? How is the app sending control data ?

### ISSUE THREAD

**Issue by vinayvinu9876** [DronaAviation/Pluto-V3R-Sample-Codes#1]

**Comment by prasannashevare** [comment]
app / pc can talk to a Pluto drone using the onboard wifi hotspot.
1. Connect to the wifi hotspot
2. telnet to the ip 192.168.4.1:23
3. Use the following link for protocols of control:
https://create.dronaaviation.com/software/remote-programming/make-your-own

**Comment by vinayvinu9876** [comment]
Can you please share an sample code sending commands with that packet structure ? It would be hugely beneficial for beginners like me.
